### ISSUE TITLE
Bug in Project Notebook.ipynb

### ISSUE THREAD

**Issue by dongdongzi** [Umar-Saeed-97/Vehicle-In-Out-Count#3]
Traceback (most recent call last):
  File "C:\Users\ISSTECH\Desktop\yolov8\Yolov8-Vehicle-Count-main\infer.py", line 105, in <module>
    line_end=(917, 387))
  File "C:\Users\ISSTECH\Desktop\yolov8\Yolov8-Vehicle-Count-main\infer.py", line 81, in vehicle_count
    in detections]
  File "C:\Users\ISSTECH\Desktop\yolov8\Yolov8-Vehicle-Count-main\infer.py", line 79, in <listcomp>
    labels = [f"{tracker_id} {model.model.names[class_id]} {confidence:0.2f}"
ValueError: too many values to unpack (expected 4)

------------------------------------------------------------------------------------------------------------------
Can you solve this bug？thanks！

**Comment by umarsaeedalam** [comment]
Hey dongdongzi,

I apologize, but at the moment, I'm unable to address this particular bug since my current focus is dedicated to another task. However, I'd like to suggest considering an alternative approach. You might want to explore YOLO-NAS, the latest model for object detection, as an option instead of sticking with YOLOv8. 

Cheers!

**Comment by dongdongzi** [comment]
> Hey dongdongzi,
> 
> I apologize, but at the moment, I'm unable to address this particular bug since my current focus is dedicated to another task. However, I'd like to suggest considering an alternative approach. You might want to explore YOLO-NAS, the latest model for object detection, as an option instead of sticking with YOLOv8.
> 
> Cheers!

OK, thanks for your reply
